### PR TITLE
fix: remove dead code and duplication

### LINKED ISSUE #1061: Rust 1.83 causing warnings in "maturin develop"
### Bug Description

I just updated to Rust 1.83.0 now my build is getting lots of these warnings

```
warning: non-local `impl` definition, `impl` blocks should be written at the same level as their item
  --> src/server.rs:62:1
   |
62 | #[pymethods]
   | -^^^^^^^^^^^
   | |
   | `PyClassImplCollector` is not local
   | `PyClassNewTextSignature` is not local
   | move the `impl` block outside of this function `trampoline` and up 4 bodies
63 | impl Server {
   |      ------
   |      |
   |      `Server` is not local
   |      `Server` is not local
   |
   = note: the attribute macro `pymethods` defines the non-local `impl`, and may need to be changed
   = note: the attribute macro `pymethods` may come from an old version of the `pyo3_macros` crate, try updating your dependency with `cargo update -p pyo3_macros`
   = note: an `impl` is never scoped, even when it is nested inside an item, as it may impact type checking outside of that item, which can be the case if neither the trait or the self type are at the same nesting level as the `impl`
   = note: `#[warn(non_local_definitions)]` on by default
   = note: this warning originates in the attribute macro `pymethods` (in Nightly builds, run with -Z macro-backtrace for more info)

```

### Steps to Reproduce

1. Upgrade to Rust 1.83
2. maturin develop

### Your operating system

Linux

### Your Python version (`python --version`)

3.12

### Your Robyn version

main branch

### Additional Info

_No response_

### PR DESCRIPTION
**Pull request by sansyrox**
## Description

This PR fixes #1061 

## Summary

This PR fixes dead code and some duplication collision

## PR Checklist

Please ensure that:

- [x] The PR contains a descriptive title
- [x] The PR contains a descriptive summary of the changes
- [x] You build and test your changes before submitting a PR.
- [x] You have added relevant documentation
- [x] You have added relevant tests. We prefer integration tests wherever possible

## Pre-Commit Instructions:

- [ ] Ensure that you have run the [pre-commit hooks](https://github.com/sparckles/robyn#%EF%B8%8F-to-develop-locally) on your PR.

### CODE REVIEW

**Comment by k4976** [comment]
I think #1061 was already solved and shipped in robyn 0.69 or 0.70 something

File: src/types/response.rs [hunk 1]
```diff
@@ -39,13 +39,6 @@ pub enum ResponseType {
 }
 
 impl ResponseType {
-    pub fn headers(&self) -> &Headers {
-        match self {
-            ResponseType::Standard(response) => &response.headers,
-            ResponseType::Streaming(streaming_response) => &streaming_response.headers,
```
Comment (k4976) [inline src/types/response.rs:45]: @sansyrox 
why streaming response being removed?
