### PR TITLE
fix: bug Binary type Reponse causes a crash#874

### LINKED ISSUE #874: Binary type Reponse causes a crash
### Bug Description

I use Robyn to write the Export Excel function, which works fine with very early versions and always crashes when updated to recent versions. I read the rust code and found that Response does a Utf8 conversion of all returned data was the cause of the crashes, then I tried to tweak the code (not knowing rust at all, AI and PyO3 docs) to differentiate between text, binary `description` Luckily the crashes disappeared!

I guessed the type of Response data by Content-Type, but there are so many MIME-Types that I thought maybe only guessing on the most common types to determine and allow users to register if the MIME-Type they use is a Text type ......

These are some of my attempts to fix this problem, I hope to get an official fix, and I wish Robyn is getting better and better, I really like it too much.

### Steps to Reproduce

1. response `Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet` data

### Your operating system

Linux

### Your Python version (`python --version`)

3.11

### Your Robyn version

latest

### Additional Info

_No response_

### PR DESCRIPTION
**Pull request by asamaayako**
**Description**

This PR fixes #874  if not utf-8 data. just using Bytes. for respnose body

### CODE REVIEW

File: src/types/response.rs [hunk 1]
```diff
@@ -68,9 +68,11 @@ impl Response {
 impl ToPyObject for Response {
     fn to_object(&self, py: Python) -> PyObject {
         let headers = self.headers.clone().into_py(py).extract(py).unwrap();
-        let description = String::from_utf8(self.description.to_vec())
-            .unwrap()
-            .to_object(py);
+        let description = match String::from_utf8(self.description.to_vec()) {
+            Ok(description) => description.to_object(py),
+            Err(_) => PyBytes::new(py, &self.description.to_vec()).into(),
```
Comment (sansyrox) [inline src/types/response.rs:73]: @asamaayako , thanks for the PR. 😄 

Are these the only two possible cases?

**Review by sansyrox — APPROVED** [review]
LGTM . Great work👍

File: src/types/response.rs [hunk 2]
```diff
@@ -68,9 +68,11 @@ impl Response {
 impl ToPyObject for Response {
     fn to_object(&self, py: Python) -> PyObject {
         let headers = self.headers.clone().into_py(py).extract(py).unwrap();
-        let description = String::from_utf8(self.description.to_vec())
-            .unwrap()
-            .to_object(py);
+        let description = match String::from_utf8(self.description.to_vec()) {
```
Comment (sansyrox) [inline src/types/response.rs:71]:
```suggestion
        // The description should only be either string or binary.
        // it should raise an exception otherwise
        let description = match String::from_utf8(self.description.to_vec()) {
```

**Comment by goSeeFuture** [comment]
v0.57.1 No more crashes, thank you very much!
